# Generated by Django 4.0.3 on 2022-09-16 16:48

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Bigfurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('content', models.TextField()),
                ('photo', models.ImageField(upload_to='bigturn_photo/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.CharField(max_length=150)),
                ('contact', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bigfurn_category', to='bigfurn.category')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
