# Generated by Django 4.0.3 on 2022-09-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigfurn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigfurn',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
